//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BradescoPGP.Repositorio
{
    using System;
    using System.Collections.Generic;
    
    public partial class AplicacaoResgate
    {
        public int Id { get; set; }
        public int agencia { get; set; }
        public int conta { get; set; }
        public System.DateTime data { get; set; }
        public System.TimeSpan hora { get; set; }
        public string operacao { get; set; }
        public string perif { get; set; }
        public string produto { get; set; }
        public string terminal { get; set; }
        public decimal valor { get; set; }
        public string gerente { get; set; }
        public string advisor { get; set; }
        public string segmento { get; set; }
        public Nullable<bool> enviado { get; set; }
        public string MatriculaConsultor { get; set; }
        public bool Notificado { get; set; }
    
        public virtual AplicResgateContatos AplicResgateContatos { get; set; }
    }
}
