//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BradescoPGP.Repositorio
{
    using System;
    using System.Collections.Generic;
    
    public partial class AplicResgateContatos
    {
        public int IdAplicResgate { get; set; }
        public Nullable<bool> ContatouCliente { get; set; }
        public Nullable<bool> Realocou { get; set; }
        public Nullable<bool> PagamentosUsoDoRecurso { get; set; }
        public Nullable<bool> AplicouEmOutroBanco { get; set; }
        public Nullable<bool> ProblemasDeRelacionamento { get; set; }
        public Nullable<bool> VaiAnalisarOferta { get; set; }
    
        public virtual AplicacaoResgate AplicacaoResgate { get; set; }
    }
}
