//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BradescoPGP.Repositorio
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PGPEntities : DbContext
    {
        public PGPEntities()
            : base("name=PGPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Aniversarios> Aniversarios { get; set; }
        public virtual DbSet<AplicacaoResgate> AplicacaoResgate { get; set; }
        public virtual DbSet<Clusterizacoes> Clusterizacoes { get; set; }
        public virtual DbSet<Cockpit> Cockpit { get; set; }
        public virtual DbSet<Configuracoes> Configuracoes { get; set; }
        public virtual DbSet<Corretora> Corretora { get; set; }
        public virtual DbSet<Evento> Evento { get; set; }
        public virtual DbSet<Fundos> Fundos { get; set; }
        public virtual DbSet<Links> Links { get; set; }
        public virtual DbSet<Motivo> Motivo { get; set; }
        public virtual DbSet<Notificacoes> Notificacoes { get; set; }
        public virtual DbSet<Origem> Origem { get; set; }
        public virtual DbSet<Perfil> Perfil { get; set; }
        public virtual DbSet<Pipeline> Pipeline { get; set; }
        public virtual DbSet<Produtividade> Produtividade { get; set; }
        public virtual DbSet<Qualitativo> Qualitativo { get; set; }
        public virtual DbSet<Solicitacao> Solicitacao { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<SubMotivo> SubMotivo { get; set; }
        public virtual DbSet<SubStatus> SubStatus { get; set; }
        public virtual DbSet<TED> TED { get; set; }
        public virtual DbSet<TEDFaixaEquipe> TEDFaixaEquipe { get; set; }
        public virtual DbSet<TedsAplicacoes> TedsAplicacoes { get; set; }
        public virtual DbSet<TedsContatos> TedsContatos { get; set; }
        public virtual DbSet<TedsMotivoOutrasInst> TedsMotivoOutrasInst { get; set; }
        public virtual DbSet<TedsMotivos> TedsMotivos { get; set; }
        public virtual DbSet<TedsProdutos> TedsProdutos { get; set; }
        public virtual DbSet<TemInvestFacil> TemInvestFacil { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<Vencimento> Vencimento { get; set; }
        public virtual DbSet<vw_MotivosSemSubmotivos> vw_MotivosSemSubmotivos { get; set; }
        public virtual DbSet<WindowsServiceConfig> WindowsServiceConfig { get; set; }
        public virtual DbSet<CaptacaoLiquidaResumo> CaptacaoLiquidaResumo { get; set; }
        public virtual DbSet<AplicResgateContatos> AplicResgateContatos { get; set; }
        public virtual DbSet<Encarteiramento> Encarteiramento { get; set; }
        public virtual DbSet<vwClusterTopTier> vwClusterTopTier { get; set; }
        public virtual DbSet<vw_CaminhoDinheiroAgrupado> vw_CaminhoDinheiroAgrupado { get; set; }
        public virtual DbSet<Investfacil> Investfacil { get; set; }
        public virtual DbSet<InvestFacilResumo> InvestFacilResumo { get; set; }
        public virtual DbSet<CaminhoDinheiro> CaminhoDinheiro { get; set; }
        public virtual DbSet<CaptacaoLiquida> CaptacaoLiquida { get; set; }
    }
}
