//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BradescoPGP.Repositorio
{
    using System;
    using System.Collections.Generic;
    
    public partial class CaminhoDinheiro
    {
        public int Id { get; set; }
        public string MesDataBase { get; set; }
        public string Ag_Conta { get; set; }
        public string Agencia { get; set; }
        public string Segmento { get; set; }
        public string Produto { get; set; }
        public decimal VL_APLIC { get; set; }
        public decimal VL_RESG { get; set; }
        public decimal PERC_DINHEIRO_NOVO { get; set; }
        public decimal PERC_CDB { get; set; }
        public decimal PERC_ISENTOS { get; set; }
        public decimal PERC_COMPROMISSADAS { get; set; }
        public decimal PERC_LF { get; set; }
        public decimal PERC_FUNDOS { get; set; }
        public decimal PERC_CORRET { get; set; }
        public decimal PERC_PREVI { get; set; }
        public decimal PERC_MSM_TIT_ENV_TOTAL { get; set; }
        public decimal PERC_DIF_TIT_ENV_TOTAL { get; set; }
        public decimal PERC_OUTROS { get; set; }
        public string MatriculaConsultor { get; set; }
        public string Consultor { get; set; }
        public string MatriculaCordenador { get; set; }
        public string Cordenador { get; set; }
    }
}
