//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BradescoPGP.Repositorio
{
    using System;
    using System.Collections.Generic;
    
    public partial class CaptacaoLiquida
    {
        public int Id { get; set; }
        public string Agencia { get; set; }
        public string Conta { get; set; }
        public string Ag_Conta { get; set; }
        public string CodAgencia { get; set; }
        public string MesDataBase { get; set; }
        public string Diretoria { get; set; }
        public string TipoPessoa { get; set; }
        public string GerenciaRegional { get; set; }
        public string MatriculaCordenador { get; set; }
        public string CordenadorPGP { get; set; }
        public string MatriculaConsultor { get; set; }
        public string Consultor { get; set; }
        public Nullable<System.DateTime> DataBase { get; set; }
        public string Produto { get; set; }
        public decimal ValorAplicacao { get; set; }
        public decimal ValorResgate { get; set; }
        public decimal ValorNET { get; set; }
    }
}
