//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BradescoPGP.Repositorio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clusterizacoes
    {
        public int Id { get; set; }
        public int CONTA { get; set; }
        public int AGENCIA { get; set; }
        public string CPF_CNPJ { get; set; }
        public string PERFIL_API { get; set; }
        public string MES_VCTO_API { get; set; }
        public string NIVEL_DESENQ_FX_RISCO { get; set; }
        public decimal SALDO_TOTAL_M3 { get; set; }
        public decimal SALDO_TOTAL { get; set; }
        public decimal SALDO_CORRETORA_BRA { get; set; }
        public decimal SALDO_CORRETORA_AGORA { get; set; }
        public decimal SALDO_CORRETORA { get; set; }
        public decimal SALDO_PREVIDENCIA { get; set; }
        public decimal SALDO_POUPANCA { get; set; }
        public decimal SALDO_INVESTS { get; set; }
        public decimal SALDO_DAV_20K { get; set; }
        public decimal SALDO_COMPROMISSADAS { get; set; }
        public decimal SALDO_ISENTOS { get; set; }
        public decimal SALDO_LF { get; set; }
        public decimal SALDO_CDB { get; set; }
        public decimal SALDO_FUNDOS { get; set; }
        public string COD_GER_RELC { get; set; }
        public string GER_RELC { get; set; }
        public string Situacao { get; set; }
        public string Segmento { get; set; }
        public string DiretoriaRegional { get; set; }
        public string CodDiretoriaRegional { get; set; }
        public string AREA { get; set; }
        public string ACAO { get; set; }
        public string ACAO_PRINCIPAL { get; set; }
    }
}
