//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BradescoPGP.Repositorio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cockpit
    {
        public int Id { get; set; }
        public int CodFuncionalGerente { get; set; }
        public string NomeGerente { get; set; }
        public string CPF { get; set; }
        public string NomeCliente { get; set; }
        public int CodigoAgencia { get; set; }
        public string NomeAgencia { get; set; }
        public int Conta { get; set; }
        public Nullable<System.DateTime> DataEncarteiramento { get; set; }
        public System.DateTime DataContato { get; set; }
        public Nullable<System.DateTime> DataRetorno { get; set; }
        public string Observacao { get; set; }
        public bool ContatoTeveExito { get; set; }
        public Nullable<System.DateTime> DataHoraEdicaoContato { get; set; }
        public string MeioContato { get; set; }
        public bool ClienteNaoLocalizado { get; set; }
        public string TipoTransacao { get; set; }
        public Nullable<bool> Finalizado { get; set; }
        public Nullable<int> GerenteRegistrouContato { get; set; }
        public string MatriculaConsultor { get; set; }
    }
}
