//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BradescoPGP.Repositorio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Encarteiramento
    {
        public int Id { get; set; }
        public string TIP_CLIENTE { get; set; }
        public string CPF { get; set; }
        public Nullable<System.DateTime> DATA { get; set; }
        public string Agencia { get; set; }
        public string Conta { get; set; }
        public string AG_PRINC { get; set; }
        public string CONTA_PRINC { get; set; }
        public string CONSULTOR { get; set; }
        public string Matricula { get; set; }
        public string EQUIPE_RESPONSAVEL { get; set; }
        public string EQUIPE_MESA { get; set; }
        public string DIR_REG_AG_PRINC { get; set; }
        public string GER_REG_AG_PRINC { get; set; }
        public Nullable<int> COD_REG { get; set; }
        public Nullable<int> COD_DIR { get; set; }
        public string AREA { get; set; }
    }
}
