//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BradescoPGP.Repositorio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Evento
    {
        public int Id { get; set; }
        public string Titulo { get; set; }
        public string Nome { get; set; }
        public string Descricao { get; set; }
        public System.DateTime DataHoraInicio { get; set; }
        public System.DateTime DataFim { get; set; }
        public string MatriculaConsultor { get; set; }
        public bool Finalizado { get; set; }
        public bool Notificado { get; set; }
    }
}
