//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BradescoPGP.Repositorio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Investfacil
    {
        public int Id { get; set; }
        public string AGENCIA { get; set; }
        public decimal Vlr_Evento { get; set; }
        public string CONTA { get; set; }
        public string SEGMENTO_CLIENTE { get; set; }
        public string NUM_CONTRATO { get; set; }
        public string MES_DT_BASE { get; set; }
        public Nullable<System.DateTime> DT_EMISSAO { get; set; }
        public Nullable<int> PRAZO_PERMAN { get; set; }
        public string FX_PERMANENCIA { get; set; }
        public string FX_VOLUME { get; set; }
        public string SEGM_AGRUPADO { get; set; }
        public string SEGMENTO_MACRO { get; set; }
        public string MatriculaConsultor { get; set; }
        public string NomeConsultor { get; set; }
        public string MatriculaCordenador { get; set; }
        public string NomeCordenador { get; set; }
        public string Plataforma { get; set; }
    }
}
