//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BradescoPGP.Repositorio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produtividade
    {
        public int Id { get; set; }
        public string Parametro { get; set; }
        public decimal ValorPercerntualMinino { get; set; }
        public System.DateTime De { get; set; }
    }
}
