//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BradescoPGP.Repositorio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Qualitativo
    {
        public int Id { get; set; }
        public string NomeConsultor { get; set; }
        public int OBJETIVOTOTAL { get; set; }
        public int DENTRODACARTEIRA { get; set; }
        public int FORADACARTEIRA { get; set; }
        public int TOTALCONTATOS { get; set; }
        public string PORCENTAGEMATINGIMENTO { get; set; }
        public int GIRODECARTEIRAOBJETIVO { get; set; }
        public int GIRODECARTEIRAOREALIZADO { get; set; }
        public string PORCENTAGEMATINGIMENTOGIRO { get; set; }
        public string REVISAOFINANCEIRAOBJETIVO { get; set; }
        public int REVISAOFINANCEIRAREALIZADO { get; set; }
        public string PORCENTAGEMATINGIMENTOREVISAO { get; set; }
        public string CADASTROAPIOBJETIVO { get; set; }
        public double CADASTROAPIREALIZADO { get; set; }
        public string PORCENTAGEMATINGIMENTOCADASTROAPI { get; set; }
        public string MatriculaConsultor { get; set; }
    }
}
