//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BradescoPGP.Repositorio
{
    using System;
    using System.Collections.Generic;
    
    public partial class TED
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TED()
        {
            this.TedsAplicacoes = new HashSet<TedsAplicacoes>();
        }
    
        public int Id { get; set; }
        public System.DateTime Data { get; set; }
        public string Agencia { get; set; }
        public string Conta { get; set; }
        public string NomeCliente { get; set; }
        public string MatriculaConsultor { get; set; }
        public string NomeConsultor { get; set; }
        public string MatriculaSupervisor { get; set; }
        public string NomeSupervisor { get; set; }
        public string Area { get; set; }
        public decimal Valor { get; set; }
        public Nullable<decimal> ValorAplicado { get; set; }
        public Nullable<int> MotivoId { get; set; }
        public int StatusId { get; set; }
        public bool Notificado { get; set; }
        public Nullable<int> MotivoTedId { get; set; }
        public Nullable<int> OutrasInstId { get; set; }
        public string Observacao { get; set; }
        public string CpfCnpj { get; set; }
    
        public virtual Motivo Motivo { get; set; }
        public virtual Status Status { get; set; }
        public virtual TedsMotivos TedsMotivos { get; set; }
        public virtual TedsMotivoOutrasInst TedsMotivoOutrasInst { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TedsAplicacoes> TedsAplicacoes { get; set; }
        public virtual TedsContatos TedsContatos { get; set; }
    }
}
