//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BradescoPGP.Repositorio
{
    using System;
    using System.Collections.Generic;
    
    public partial class TedsContatos
    {
        public int IdTed { get; set; }
        public Nullable<bool> ContatouCliente { get; set; }
        public Nullable<bool> ContatouGerente { get; set; }
        public Nullable<bool> GerenteSolicitouNaoAtuacao { get; set; }
        public Nullable<bool> GerenteInvestimentoAtuou { get; set; }
        public Nullable<bool> EspecialistaAtuou { get; set; }
        public Nullable<bool> ClienteLocalizado { get; set; }
        public Nullable<bool> ClienteAceitaConsultoria { get; set; }
    
        public virtual TED TED { get; set; }
    }
}
