//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BradescoPGP.Repositorio
{
    using System;
    using System.Collections.Generic;
    
    public partial class TedsAplicacoes
    {
        public int Id { get; set; }
        public int IdTed { get; set; }
        public int IdProduto { get; set; }
        public decimal ValorAplicado { get; set; }
    
        public virtual TED TED { get; set; }
        public virtual TedsProdutos TedsProdutos { get; set; }
    }
}
