//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BradescoPGP.Repositorio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vencimento
    {
        public int Id { get; set; }
        public int Cod_Agencia { get; set; }
        public int Cod_Conta_Corrente { get; set; }
        public System.DateTime Dt_Vecto_Contratado { get; set; }
        public string Nm_Cliente_Contraparte { get; set; }
        public double Perc_Indexador { get; set; }
        public string Nome_produto_sistema_origem { get; set; }
        public decimal SALDO_ATUAL { get; set; }
        public Nullable<int> StatusId { get; set; }
    
        public virtual Status Status { get; set; }
    }
}
