//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BradescoPGP.Repositorio
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_CaminhoDinheiroAgrupado
    {
        public string MesDataBase { get; set; }
        public string MatriculaCordenador { get; set; }
        public string Cordenador { get; set; }
        public string MatriculaConsultor { get; set; }
        public string Consultor { get; set; }
        public string Produto { get; set; }
        public Nullable<decimal> CAPLIQ { get; set; }
        public Nullable<decimal> VL_APLIC { get; set; }
        public Nullable<decimal> PERC_NEWMONEY { get; set; }
        public Nullable<decimal> VL_RESG { get; set; }
        public Nullable<decimal> PERC_CDB { get; set; }
        public Nullable<decimal> PERC_ISENTOS { get; set; }
        public Nullable<decimal> PERC_CPMSS { get; set; }
        public Nullable<decimal> PERC_LF { get; set; }
        public Nullable<decimal> PERC_FDOS { get; set; }
        public Nullable<decimal> PERC_CORRET { get; set; }
        public Nullable<decimal> PERC_PREVI { get; set; }
        public Nullable<decimal> PERC_MSM_TIT_ENV_TOTAL { get; set; }
        public Nullable<decimal> PERC_DIF_TIT_ENV_TOTAL { get; set; }
        public Nullable<decimal> PERC_OUTROS { get; set; }
    }
}
