//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BradescoPGP.Repositorio
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwClusterTopTier
    {
        public string CONSULTOR { get; set; }
        public int AGENCIA { get; set; }
        public int CONTA { get; set; }
        public string CPF_CNPJ { get; set; }
        public string GER_RELC { get; set; }
        public string ACAO { get; set; }
        public string NIVEL_DESENQ_FX_RISCO { get; set; }
        public string PERFIL_API { get; set; }
        public decimal SALDO_TOTAL { get; set; }
        public decimal SALDO_PREVIDENCIA { get; set; }
        public string ACAO_PRINCIPAL { get; set; }
    }
}
