//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BradescoPGP.Repositorio
{
    using System;
    using System.Collections.Generic;
    
    public partial class WindowsServiceConfig
    {
        public int Id { get; set; }
        public string Tarefa { get; set; }
        public string CaminhoOrigem { get; set; }
        public System.DateTime UltimaExecucao { get; set; }
        public string IntervaloExecucao { get; set; }
        public Nullable<System.DateTime> DataUltimaModificacao { get; set; }
        public string PadraoPesquisa { get; set; }
        public Nullable<bool> Acrescentar { get; set; }
        public string UltimoArquivo { get; set; }
        public bool EmExecucao { get; set; }
        public string NomeArquivo { get; set; }
        public bool TeveFalha { get; set; }
    }
}
